[values]
poll_interval_ms={{poll_interval_ms}}
temp_log_interval_ms={{temp_log_interval_ms}}
freq_log_interval_ms={{freq_log_interval_ms}}
power_log_interval_ms={{power_log_interval_ms}}
csv_write_interval_ms={{csv_write_interval_ms}}
{{#profiles}}

; {{name}}
[{{id}}]
{{#clocks}}
{{key}}={{value}}
{{/clocks}}
{{/profiles}}
